name: tcb_recru_task
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  cached_network_image: ^3.3.0
  chopper: ^8.3.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.1.0
  hooked_bloc: ^1.7.0
  injectable: ^2.5.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  simple_chopper_logger: ^2.0.0
  theme_tailor_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.6.0
  chopper_generator: ^8.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.8.0
  json_serializable: ^6.10.0
  theme_tailor: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
